### ISSUE TITLE
Tags are causing Swift Package confusion

### ISSUE THREAD

**Issue by brindy** [toddheasley/zxcvbn#1]
Hi @toddheasley - nice work with this! 

I’m just giving it a try and I notice that Xcode wants me to use 1.0.4 but then complains there’s no Package.swift file for that version. Looks like you maybe have some tags from the upstream there?  Is it worth just deleting those? 

Thanks!

**Comment by toddheasley** [comment]
Good catch! Deleted the Dropbox tags; SPM should find the package now.

**Comment by brindy** [comment]
Thanks!
